DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
sitemap:
  filename: sitemap.xml
languages:
  en:
    baseUrl: https://digital.canada.ca/
    contentDir: content/en
    lang: en
    languageName: English
    title: Blog
    Paginate: 6
    frontmatter:
      date: [":filename", ":default"]
    permalinks:
      blog: /:year/:month/:day/:filename
      work-with-us: /:title
    weight: 1
    menu:
      main:
        - identifier: products
          name: Products
          url: /products/
          weight: 1
        - identifier: about-cds
          name: About CDS
          url: /about-us/  
          weight: 2
        - identifier: blog
          name: Blog
          url: /blog/
          weight: 3     
  fr:
    baseUrl: https://numerique.canada.ca/
    contentDir: content/fr
    lang: fr
    languageName: Francais
    title: Blogue
    Paginate: 6
    weight: 2
    frontmatter:
      date: [":filename", ":default"]
    permalinks:
      blog: /:year/:month/:day/:filename
      work-with-us: /:title
    menu:
      main:
        - identifier: produits
          name: Produits
          url: /produits/
          weight: 1
        - identifier: about-us-fr
          name: About CDS FR
          url: /about-us-fr/
          weight: 2  
        - identifier: blogue
          name: Blogue
          url: /blogue/
          weight: 3      
outputs:
  home : [HTML, RSS, JSON]
  page : HTML         
