baseURL: https://digital.canada.ca/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

params:
  lever_api_endpoint: https://944yirpts7.execute-api.ca-central-1.amazonaws.com/Production/lever
  home:
    en: "content/en/products/_index.html"
    fr: "content/fr/products/_index.html"

sitemap:
  filename: sitemap.xml
  changefreq: always

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageCode: en-CA
    languageName: English
    weight: 1
    title: Blog
    contentDir: content/en
    baseURL: https://digital.canada.ca/
    paginate: 6
    params:
      region: en-CA
      locale: English (Canada)
    permalinks:
      blog: /:year/:month/:day/:filename
      work-with-us: /:title
    frontmatter:
      date: [":filename", ":default"]
    menu:
      main:
        - identifier: Products
          name: Products
          url: /
          weight: 1
        - identifier: About
          name: About
          url: /about/  
          weight: 2
        - identifier: blog
          name: Blog
          url: /blog/
          weight: 3
        - identifier: jobs
          name: Jobs at CDS
          url: /jobs/
          weight: 4
      toolkit:
        - identifier: About
          name: About
          url: /toolkit/about/  
          weight: 1

  fr:
    languageCode: fr-CA
    languageName: Français
    weight: 2
    title: Blogue
    contentDir: content/fr
    baseURL: https://numerique.canada.ca/
    paginate: 6
    params:
      region: fr-CA
      locale: Français (Canada)
    permalinks:
      blog: /:year/:month/:day/:filename
      work-with-us: /:title
    frontmatter:
      date: [":filename", ":default"]
    menu:
      main:
        - identifier: Produits
          name: Produits
          url: /
          weight: 1
        - identifier: À propos
          name: À propos
          url: /a-propos/
          weight: 2
        - identifier: blogue
          name: Blogue
          url: /blogue/
          weight: 3
        - identifier: emplois
          name: Emplois au SNC
          url: /emplois/
          weight: 4
      toolkit:
        - identifier: À propos
          name: À propos
          url: /toolkit/a-propos/
          weight: 1
outputs:
  home: [HTML, RSS, JSON]
  page: HTML

security:
  enableInlineShortcodes: true