name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    paths:
    - "terragrunt/**"
    - ".github/workflows/tf_plan_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.4.6
  TERRAGRUNT_VERSION: 0.45.11
  CONFTEST_VERSION: 0.42.1

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: s3
          - module: cloudfront
          - module: ecr 

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: set up terraform tools
      uses: cds-snc/terraform-tools-setup@v1

    - name: configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3.0.2
      with:
        role-to-assume: arn:aws:iam::521732289257:role/digital-canada-ca-website-plan   # use for TF plan or when you only need read-only access (works on all branches)
        role-session-name: TFPlan
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Plan
      uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
      with:
        comment-delete: true
        comment-title: "Production: ${{ matrix.module }}"
        directory: terragrunt/env/production/${{ matrix.module }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        terragrunt: true   

